apiVersion: apps/v1
kind: Deployment
metadata:
  name: tipsrundan-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tipsrundan-webapp
  template:
    metadata:
      labels:
        app: tipsrundan-webapp
    spec:
      containers:
      - name: tipsrundan-container
        image: ghcr.io/superellips/tipsrundan:47ee37c5ac6d481f9257be2618b4ad4c1ea2f2fa
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: app-config